name: Publish articles on dev.to
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish to dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "markdown/**/*.md"
          dry_run: ${{ github.event_name == 'pull_request' }}

      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes result:
            ```
            ${{ steps.publish_devto.outputs.result_summary }}
            ```
